[project]
name = "moco-v3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Usama Mangi", email = "usamapk7861@gmail.com" }]
dependencies = []
